Created V-0.1
NikolayFatkullin/Opera-app pull request #1
Opened 2021-01-26 15:05 UTC by NikolayFatkullin

- Created model Movie;
- Created MovieDao;
- Created MovieService;
- Created HibernateUtil;
- Created Injector;
- Created annotations: Dao, Inject;

2021-01-26 15:52 UTC, Max-Pochepets requested changes
make sure all your files have empty line in the end

2021-01-26 15:52 UTC, Max-Pochepets commented on src/main/java/com/tickets/dao/impl/MovieDaoImpl.java
> +            movie.setId(movieId);
check [this](https://mate-academy.github.io/jv-program-fulltime/03_hibernate/checklist/hibernate_01.html) one more time

2021-01-26 15:59 UTC, Max-Pochepets requested changes
what about [this](https://github.com/NikolayFatkullin/TicketsShop/pull/1#discussion_r564619897) one?

2021-01-26 16:05 UTC, Max-Pochepets approved these changes
👍

2021-01-26 16:37 UTC, Sofasmile requested changes

2021-01-26 16:37 UTC, Sofasmile commented on src/main/java/com/tickets/dao/impl/MovieDaoImpl.java
> +            throw new RuntimeException("Can't insert Movie entity", e);
let's create your own exception

2021-01-27 07:10 UTC, Sofasmile requested changes

2021-01-27 07:10 UTC, Sofasmile commented on src/main/java/com/tickets/dao/impl/MovieDaoImpl.java
> +            throw new DataProcessingException("Can't insert Movie entity", e);
```suggestion
            throw new DataProcessingException("Can't insert Movie entity " + movie, e);
```

2021-01-27 07:21 UTC, Sofasmile approved these changes

2021-01-27 07:31 UTC, merged