- Created models: CinemaHall, MovieSession.
NikolayFatkullin/Opera-app pull request #2
Opened 2021-01-31 11:50 UTC by NikolayFatkullin

- Created DAO and Service layers for new models

2021-01-31 13:40 UTC, AndreiYazadzhi approved these changes

2021-01-31 13:42 UTC, AndreiYazadzhi commented
I approved this ,but im not sure about your query.I think that this task must be solved with join fetch.If its not importent in our case all good)

2021-01-31 17:15 UTC, Max-Pochepets commented on src/main/java/com/tickets/model/MovieSession.java
> +    @ManyToOne
these annotations have `FetchType.EAGER` by default

2021-02-01 18:37 UTC, KseniiaMakarova commented
@Max-Pochepets @AndreiYazadzhi  it is ok in our case to have FetchType.EAGER for @OneToOne and @ManyToOne annotations - we only fetch 1 additional object from the DB

2021-02-01 18:44 UTC, KseniiaMakarova requested changes

2021-02-01 18:44 UTC, KseniiaMakarova commented on src/main/java/com/tickets/dao/impl/CinemaHallDaoImpl.java
> +                    .createQuery("from cinema_hall ", CinemaHall.class);
I think it is better to use class name and not the table name here - so that we could understand that in HQL we can refer to classes and their fields

2021-02-01 18:44 UTC, KseniiaMakarova commented on src/main/java/com/tickets/dao/impl/MovieSessionDaoImpl.java
> +            Query<MovieSession> query = session.createQuery("FROM movie_session "
same here

2021-02-01 18:44 UTC, KseniiaMakarova commented on src/main/java/com/tickets/model/MovieSession.java
> +    private LocalDateTime showTime;
let's use let's use `@JoinColumn` annotation so that our columns would have the `right_naming` - and not `camelCaseName`

2021-02-01 18:44 UTC, KseniiaMakarova commented on src/main/java/com/tickets/service/CinemaHallService.java
> +@Service
do we need this here?

2021-02-01 18:44 UTC, KseniiaMakarova commented on src/main/java/com/tickets/service/MovieSessionService.java
> +@Service
same

2021-02-02 06:18 UTC, KseniiaMakarova approved these changes

2021-02-02 06:18 UTC, KseniiaMakarova commented on src/main/java/com/tickets/model/MovieSession.java
>      private LocalDateTime showTime;
@JoinColumn(name = "show_time")

2021-02-02 07:15 UTC, merged