- Created models: Ticket, ShoppingCart;
NikolayFatkullin/Opera-app pull request #4
Opened 2021-02-03 16:10 UTC by NikolayFatkullin

- Created DAO layers for new models;
- Created service ShoppingCartService;
- Added method register registerNewShoppingCart to method register in AuthenticationServiceImpl

2021-02-03 16:28 UTC, Fedich09 approved these changes

2021-02-04 07:44 UTC, KseniiaMakarova requested changes

2021-02-04 07:44 UTC, KseniiaMakarova commented on src/main/java/com/tickets/Main.java
> +        System.out.println(ticketDao.add(ticket));
we should test only services in main()

2021-02-04 07:44 UTC, KseniiaMakarova commented on src/main/java/com/tickets/security/impl/AuthenticationServiceImpl.java
redundant empty line

2021-02-04 07:44 UTC, KseniiaMakarova commented on src/main/java/com/tickets/service/impl/ShoppingCartServiceImpl.java
> +
same

2021-02-04 09:12 UTC, KseniiaMakarova approved these changes

2021-02-04 09:48 UTC, merged