- Created model Order and Dao layer for her;
NikolayFatkullin/Opera-app pull request #5
Opened 2021-02-04 13:54 UTC by NikolayFatkullin

- Created OrderService;

2021-02-04 15:17 UTC, Fedich09 approved these changes

2021-02-04 16:56 UTC, dmytro-hryhoruk requested changes

2021-02-04 16:56 UTC, dmytro-hryhoruk commented on src/main/java/com/tickets/dao/impl/OrderDaoImpl.java
> +            return session.createQuery("FROM Order o LEFT JOIN FETCH o.tickets "
https://mateacademy.slack.com/archives/G01EHB8CWAE/p1612455330236200

2021-02-05 09:56 UTC, dmytro-hryhoruk approved these changes

2021-02-05 10:26 UTC, merged