- Added supporting of Spring to project
NikolayFatkullin/Opera-app pull request #6
Opened 2021-02-11 14:10 UTC by NikolayFatkullin

- Deleted redundant annotations and configurations

2021-02-11 14:37 UTC, semyonich approved these changes

2021-02-11 16:09 UTC, Sofasmile requested changes
HibernateUtil should be removed

2021-02-12 07:29 UTC, Sofasmile requested changes

2021-02-12 07:29 UTC, Sofasmile commented on src/main/java/com/tickets/config/AppConfig.java
> +        "com.tickets.dao"
let's add `security` package here

2021-02-12 08:27 UTC, Sofasmile approved these changes

2021-02-12 08:37 UTC, merged