- Added DTO to the models CinemaHall, Movie, MovieSession
NikolayFatkullin/Opera-app pull request #7
Opened 2021-02-14 17:58 UTC by NikolayFatkullin

- Added MovieSessionController, CinemaHallController, MovieController
- Added mappers to the DTOs

2021-02-14 21:49 UTC, Fedich09 approved these changes

2021-02-15 07:13 UTC, boroda4436 requested changes

2021-02-15 07:13 UTC, boroda4436 commented on src/main/java/com/tickets/controller/MovieSessionController.java
> +    public void updateSession(@RequestParam Long id,
is it ok to use `@RequestParam` according to [REST Resource Naming Guide](https://restfulapi.net/resource-naming/)?

2021-02-15 07:13 UTC, boroda4436 commented on src/main/java/com/tickets/controller/MovieSessionController.java
> +            @RequestParam Long id, @RequestParam @DateTimeFormat(pattern = "dd.MM.yyyy")
Is this `id` an identifier of MovieSession? If yes why you are using RequestParam? If no, let's rename

2021-02-15 07:13 UTC, boroda4436 commented on src/main/java/com/tickets/service/dto/impl/MovieSessionMapperImpl.java
> +package com.tickets.service.dto.impl;
better to name package `mapper` or `mappers` instead of `dto`

2021-02-15 12:43 UTC, boroda4436 approved these changes

2021-02-15 12:43 UTC, boroda4436 commented on src/main/java/com/tickets/controller/MovieSessionController.java
> +    @PutMapping("{id}")
good, better write /{id}

2021-02-15 13:19 UTC, merged